; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy_hid_device]
platform = teensy
framework = arduino
board = teensy41
lib_deps = lathoub/USB-MIDI@^1.1.3
build_flags = 
    -DUSB_MIDI=1
    -DUSB_MIDI_SERIAL=0
    -DUSB_MIDI_INTERFACE=1
    -DMIDI_NUM_CABLES=16
		-DMIDI_INTERFACE=1
    -UUSB_SERIAL
    -UUSB_HID
    -UUSB_RAWHID
    -UUSB_FLIGHTSIM
    -UUSB_VIRTUAL
    -UUSB_FTDI
    -UUSB_XINPUT

